[tool.poetry]
name = "time_series"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8, <3.12"
nbformat = "5.4.0"
sktime = "^0.18.0"
scikit-learn = "^1.2.2"
pmdarima = "^2.0.3"
mlflow = "^2.11.3"
ipykernel = "^6.29.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
